title: I am Khoa
subtitle: ⟶
description: >- # this means to ignore newlines until "baseurl:"
  # I am passionate about building privacy-preserving medical AI applications

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    # - text: Gallery
      # url: /gallery
    # - text: Shop
    #   url : /shop
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: khoa.png
author: Khoa
author_bio: "Hi, my name is Khoa. Currently, I am working as a researcher at the Network & Information 
Security Research Group, Tampere University, Finland under supervision of Prof. Antonios Michalas and a software engineer intern at OpenMined.
I graduated with my bachelor and master degree from the Computing Sciences department also at Tampere University. 
During my bachelor study, I worked as a research assistant at the the centre for immersive visual technologies (CIVIT) under supervision of Prof. Atanas Gotchev. \n
I am passionate about building privacy-preserving AI applications for healthcare and medicine. 
This blog is where I share my learning journey and other passions in life. 
In my free time, I enjoy training boxing and calisthenics, playing guitar, reading, writing..."
author_email: "dkn.work@protonmail.com"
author_location: I am a cyberghost 👻
# author_website_url: "https://khoaduynguyen.com"
typewrite-text: I am passionate about building privacy-preserving medical AI applications
hero_cover_img: ai-banner.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: OpenMined
              company_logo: openmined.png
              company_url: https://www.openmined.org/
              designation: Software Engineer Intern
              description: Accepted into the OpenMined Padawan program (https://blog.openmined.org/tag/padawan-program/) to learn and contribute to PySyft - a privacy-preserving deep learning framework
              visibility: true
            - company_name: Network and Information Security Research Group (NISEC)
              company_logo: nisec.jpg
              company_url: https://research.tuni.fi/nisec/
              designation: Researcher
              description: Working on privacy-preserving AI applications for healthcare and medicine
              visibility: true
            - company_name: Centre for Immersive Visual Technologies (CIVIT)
              company_logo: civit.png
              company_url: https://civit.fi
              designation: Research Assistant
              description: Working on AI applications into object detection and localization
              visibility: true

# Education
author_education_details:
              - college_logo: tuni.png
                college_name: Tampere University, Finland
                college_url: https://tuni.fi
                college_degree: Master of  Machine Learning and Cyber Security
                description: Full Tuition Scholarship. Graduate with Distinction
                visibility: true
              - college_logo: tuni.png
                college_name: Tampere University, Filand
                college_url: https://tuni.fi
                college_degree: Bachelor of Information Technology
                description: Full Tuition Scholarship
                visibility: true
              - college_logo: HCMCUT.png
                college_name: Ho Chi Minh City University of Technology, Vietnam
                college_url: https://oisp.hcmut.edu.vn/en/
                college_degree: Bachelor of Electrical Engineering
                description:  Dropped out to pursue my dream of studing abroad
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: projects/harpocrates.png
                project_title: HARPOCRATES
                project_description: Designing practical cryptographic schemes for analysing data in a privacy-preserving way 
                project_url: https://harpocrates-project.eu/
                visibility: true
              - project_thumbnail: projects/pysyft.png
                project_title: PySyft
                project_description: Data science on data without acquiring a copy
                project_url: https://github.com/OpenMined/PySyft
                visibility: true

# social links
github_username:  khoaguin
linkedin_username: khoa-duy-nguyen
medium_username: khoaguin
google_scholar_username: 9Cx8YUIAAAAJ
# twitter_username: johndoe
# facebook_username: johndoe
# behance_username: johndoe
# instagram_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: khoaguin

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

  # contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: dkn.work@protonmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build

google_analytics: G-Z3DPBD2DK8   # fill in your Google Analytics ID
